image: Visual Studio 2022
version: 2.0.{build}
configuration: Release

init:
- if "%APPVEYOR_REPO_NAME%" == "JeremyAnsel/SharpSevenZip" if "%APPVEYOR_REPO_BRANCH%"=="main" if not defined APPVEYOR_PULL_REQUEST_NUMBER set DEPLOY=True

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'

environment:
  GITHUB_TOKEN:
    secure: awbDbCVBldNyz+7VzGnSLlBnczS0NtXrUaS7UkrwoOoUIAzE70QHYfKQuTyOJavb

nuget:
  disable_publish_on_pr: true

before_build:
- nuget restore SharpSevenZip\SharpSevenZip.sln

build:
  project: SharpSevenZip\SharpSevenZip.sln
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true
  verbosity: minimal

after_build:
- if not defined APPVEYOR_PULL_REQUEST_NUMBER SharpSevenZip\build-doc.cmd
- if not defined APPVEYOR_PULL_REQUEST_NUMBER 7z a SharpSevenZip.Documentation.zip .\SharpSevenZip\Documentation\_site\* > nul
- if not defined APPVEYOR_PULL_REQUEST_NUMBER appveyor PushArtifact SharpSevenZip.Documentation.zip

deploy:
- provider: NuGet
  api_key:
    secure: pKXeG1dEG4en2au1AJ2f10uvRQump9r3ojOuKXXRfWEs5rP+uAKasd14kUtT2A6+
  skip_symbols: false
  on:
    branch: main
    DEPLOY: True

after_deploy:
- if "%DEPLOY%" == "True" git clone -q --branch=gh-pages --depth 5 https://github.com/JeremyAnsel/SharpSevenZip.git gh-pages
- if "%DEPLOY%" == "True" cd gh-pages
- if "%DEPLOY%" == "True" git checkout -qf gh-pages
- if "%DEPLOY%" == "True" git config core.safecrlf false
- if "%DEPLOY%" == "True" git config push.default simple
- "if \"%DEPLOY%\" == \"True\" git config user.name \"Jérémy Ansel\""
- if "%DEPLOY%" == "True" git config user.email JeremyAnsel@users.noreply.github.com
- if "%DEPLOY%" == "True" xcopy /s /y /q ..\SharpSevenZip\Documentation\_site .
- if "%DEPLOY%" == "True" git add --all . > nul
- if "%DEPLOY%" == "True" git commit -m "Update doc generated by CI" || true
- if "%DEPLOY%" == "True" git push -q https://%GITHUB_TOKEN%@github.com/JeremyAnsel/SharpSevenZip.git
